baseURL = 'https://systemexploit.club'
languageCode = 'en-us'
title = 'System Exploit Club'
theme = 'archie'
copyright = "© SysExploitClub"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
    mode="auto"
    useCDN=false
    subtitle = "Welcome! This blog will mainly consist of vulnerablities/exploits on the windows OS that can be used to circumvent security measures implemented by Anticheats. Feel free to join our [discord!](https://discord.gg/xfMuDfK3xy)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/memcpyy"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/memcpyy/"

[[params.og_image]]
url = "https://discord.com/channels/@me/1152859945050578984/1155102855527673936"

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4